TaskManaga/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('main/', views.main, name='main')
]

TaskManaga/taskManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('user.urls', namespace='user')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'main.views.error_404_page'

TaskManaga/user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('sign-in/', views.sign_in, name='sign-in'),
    path('sign-up/', views.sign_up, name='sign-up'),
    path('check-user/', views.check_user, name='check-user'),
    path('logout/', views.logout_acc, name='logout'),
    path('password-reset/', views.password_reset, name='password_reset')
]

TaskManaga/user/models.py
import os

from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    username = models.CharField(max_length=64, unique=True)
    email = models.EmailField(max_length=255)
    firstname = models.CharField(max_length=64, null=True)
    avatar = models.ImageField(upload_to='profile/avatars/', null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def delete_avatar(self):
        if self.avatar:
            avatar_path = self.avatar.path

            if os.path.isfile(avatar_path):
                os.remove(avatar_path)

            self.avatar = None
            self.save()

    class Meta:
        db_table = 'users'

TaskManaga/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(max_length=64)
    email = forms.EmailField(max_length=255)
    password1 = forms.CharField(max_length=255)
    password2 = forms.CharField(max_length=255)

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']

TaskManaga/user/views.py
from random import randint, sample
from string import printable

from django.http import JsonResponse
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.conf import settings
from django.core.cache import cache

from .models import User
from .utils import HTML_EMAIL_CODE_MSG, get_client_ip, HTML_EMAIL_REG_CODE_MSG, HTML_PASSWORD_RESET_CODE_MSG
from .tasks import send_email
from .forms import UserRegistrationForm

# Create your views here.
REDIS_IP = 'user_ip-{id}'
REDIS_EMAIL_SUBMIT = 'user_email_submit-{id}'

def sign_in(request):
    if request.user.is_authenticated:
        return redirect(reverse('main:main'))
    if request.method == 'POST':
        data = request.POST.copy()
        if data.get('success'):
            user = authenticate(username=data.get('username'), password=data.get('password'))
            if user:
                if cache.get(REDIS_EMAIL_SUBMIT.format(id=user.id)) is None:
                    # CHANGE IT TO 3600 * 24 * 30
                    cache.set(REDIS_EMAIL_SUBMIT.format(id=user.id), 'confirmed', timeout=3600 * 24 * 30)
                if cache.get(REDIS_IP.format(id=user.id)) != get_client_ip(request):
                    cache.set(REDIS_IP.format(id=user.id), get_client_ip(request), timeout=3600 * 24 * 90)
                login(request, user)
                #   CHANGE TO NORMAL REVERSE URL
                return JsonResponse({'status': 200, 'successUrl': reverse('main:main')})
        else:
            if not User.objects.filter(username=data.get('username')).exists():
                return JsonResponse({'status': 404, 'message': 'no user with such username'})
            user = authenticate(username=data.get('username'), password=data.get('password'))
            if user:
                if cache.get(REDIS_IP.format(id=user.id)) == get_client_ip(request) and cache.get(REDIS_EMAIL_SUBMIT.format(id=user.id)):
                    login(request, user)
                    #   CHANGE TO NORMAL REVERSE URL
                    return JsonResponse({'status': 200, 'trust': 1, 'successUrl': reverse('main:main')})
                code = randint(1000, 9999)
                email = user.email
                subject = "Tasko authentication"
                from_email = settings.EMAIL_HOST_USER
                to_email = email
                html_content = HTML_EMAIL_CODE_MSG.format(username=user.username, code=code)
                send_email.delay_on_commit(subject, from_email, to_email, html_content)
                return JsonResponse({'status': 200, 'code': code, 'email': user.email})
            return JsonResponse({'status': 403, 'message': 'wrong credentials'})
    context = {
        'title': 'Tasko sign-in'
    }
    return render(request, 'user/sign-in.html', context)


def sign_up(request):
    if request.user.is_authenticated:
        return redirect(reverse('main:main'))
    if request.method == 'POST':
        if request.POST.get('sendEmail'):
            code = randint(1000, 9999)
            email = request.POST.get('email')
            username = request.POST.get('username')
            subject = "Tasko registration"
            from_email = settings.EMAIL_HOST_USER
            to_email = email
            html_content = HTML_EMAIL_REG_CODE_MSG.format(username=username, code=code)
            send_email.delay_on_commit(subject, from_email, to_email, html_content)
            return JsonResponse({'status': 200, 'code': code})
        elif request.POST.get('success'):
            username = request.POST.get('username')
            password = request.POST.get('password')
            email = request.POST.get('email')
            form = UserRegistrationForm({'username': username, 'email': email, 'password1': password, 'password2': password})
            print(form)
            if form.is_valid():
                user = form.save()
                login(request, user)
                cache.set(REDIS_EMAIL_SUBMIT.format(id=user.id), 'confirmed', timeout=3600 * 24 * 30)
                cache.set(REDIS_IP.format(id=user.id), get_client_ip(request), timeout=3600 * 24 * 90)
                return JsonResponse({'status': 201, 'successUrl': reverse('main:main')})

    context = {
        'title': 'Tasko sign-up'
    }
    return render(request, 'user/sign-up.html', context)


def check_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        if username:
            if User.objects.filter(username=username).exists():
                return JsonResponse({'status': 409, 'message': 'user with such username already exists'})
    return JsonResponse({'status': 200, 'message': 'no user with such username'})


def logout_acc(request):
    logout(request)
    return JsonResponse({'status': 200, 'url': reverse('user:sign-in')})


def password_reset(request):
    if request.method == 'POST':
        if request.POST.get('check_user'):
            username = request.POST.get('username')
            user = User.objects.filter(username=username).first()
            if user:
                code = randint(1000, 9999)
                subject = "Tasko registration"
                from_email = settings.EMAIL_HOST_USER
                to_email = user.email
                html_content = HTML_PASSWORD_RESET_CODE_MSG.format(username=username, code=code)
                send_email.delay_on_commit(subject, from_email, to_email, html_content)
                return JsonResponse({'status': 200, 'code': code, 'email': user.email})
            else:
                return JsonResponse({'status': 404, 'message': 'user with such username doesn\'t exist'})
        elif request.POST.get('startReset'):
            secret_key = ''.join(sample(printable, 32))
            return JsonResponse({'status': 200, 'secret_key': secret_key})
        elif request.POST.get('reset'):
            if request.POST.get('secretKey'):
                username = request.POST.get('username')
                password = request.POST.get('password')
                user = User.objects.filter(username=username).first()
                user.set_password(password)
                user.save()
                login(request, user)
                return JsonResponse({'status': 200, 'successUrl': reverse('main:main')})
            else:
                return JsonResponse({'status': 403, 'message': 'nuh-uh'})
    context = {
        'title': 'Tasko reset'
    }
    return render(request, 'user/password-reset.html', context)

TaskManaga/user/templates/user/password-reset.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static "user/css/password-reset.css" %}">
    <title>{{ title }}</title>
</head>
<body>
    <input type="hidden" name="sendUrl" value="{% url "user:password_reset" %}">
    <div class="wrong-message none">
        <h2>Нет пользователя с таким логином</h2>
    </div>
    <form method="post" class="firs block">
        {% csrf_token %}
        <label for="login">Логин</label>
        <div class="input">
            <input type="text" name="login" id="login">
        </div>
        <div class="start dataF">
             <button>поменять пароль</button>
        </div>
        <a class="have" href="{% url "user:sign-in" %}">Я вспомнил пароль</a>
    </form>
    <form method="post" class="secon block none">
        {% csrf_token %}
        <p class="emailP"></p>
        <p class="tries">осталось попыток 5</p>
        <label for="code">Введите код</label>
        <div class="input code">
            <input type="text" name="code" id="code">
        </div>
        <div class="start emailF">
             <button>продолжить</button>
        </div>
        <div class="back">
            <a href="{% url "user:password_reset" %}">назад</a>
        </div>
    </form>
    <form method="post" class="third block none">
        {% csrf_token %}
        <label for="password">Пароль</label>
        <div class="input">
            <input type="password" name="password" id="password">
        </div>
        <label for="password2">Повторите пароль</label>
        <div class="input">
            <input type="password" name="password2" id="password2">
        </div>
        <div class="start resF">
             <button>поменять пароль</button>
        </div>
        <a class="have" href="{% url "user:sign-in" %}">Я вспомнил пароль</a>
    </form>

    <script
        src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
        crossorigin="anonymous">
    </script>
    <script src="{% static "user/js/password-reset.js" %}"></script>
</body>
</html>

TaskManaga/user/templates/user/sign-in.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "user/css/sign-in.css" %}">
    <link rel="stylesheet" href="{% static "user/css/sign-in-submit.css" %}">
    <title>{{ title }}</title>
</head>
<body>
    <input type="hidden" name="sendUrl" value="{% url "user:sign-in" %}">
    <div class="wrong-message none">
        <h2>Нет пользователя с таким логином</h2>
    </div>
    <form method="post" class="firs block">
        {% csrf_token %}
        <label for="login">Ваш логин</label>
        <div class="input">
            <input type="text" name="login" id="login">
        </div>
        <label for="password">Ваш пароль</label>
        <div class="input">
            <input type="password" name="password" id="password">
        </div>
        <div class="start dataF">
             <button>войти</button>
        </div>
        <a class="have" href="{% url "user:sign-up" %}">У меня нет аккаунта</a>
        <a href="{% url "user:password_reset" %}" class="have">Забыл пароль</a>
    </form>
    <form method="post" class="secon block none">
        {% csrf_token %}
        <p class="emailP"></p>
        <p class="tries">осталось попыток 5</p>
        <label for="code">Введите код</label>
        <div class="input code">
            <input type="text" name="code" id="code">
        </div>
        <div class="start emailF">
             <button>продолжить</button>
        </div>
        <div class="back">
            <a href="{% url "user:sign-in" %}">назад</a>
        </div>
    </form>

    <script
        src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
        crossorigin="anonymous">
    </script>
    <script src="{% static "user/js/sign-in.js" %}"></script>
</body>
</html>

TaskManaga/user/templates/user/sign-up.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "user/css/sign-up.css" %}">
    <title>{{ title }}</title>
</head>
<body>
    <input type="hidden" name="checkUrl" value="{% url "user:check-user" %}">
    <input type="hidden" name="sendUrl" value="{% url "user:sign-up" %}">
    <div class="wrong-message none">
        <h2 class="diff-pass none">Пароли не совпадают</h2>
        <h2 class="taken-login none">Логин занят</h2>
        <h2 class="not-all none">Заполнено не всё</h2>
        <h2 class="pasvalid none" style="font-size: 1.25rem;">Убедитесь, что в пароле минимум 8 символов, среди которых хотя-бы одна цифра, символ и заглавная буква</h2>
    </div>
    <form method="post" class="firs block">
        {% csrf_token %}
        <label for="login">Логин</label>
        <div class="input">
            <input type="text" name="login" id="login">
        </div>
        <label for="email">Почта</label>
        <div class="input">
            <input type="email" name="email" id="email">
        </div>
        <label for="password">Пароль</label>
        <div class="input">
            <input type="password" name="password" id="password">
        </div>
        <label for="password2">Повторите пароль</label>
        <div class="input">
            <input type="password" name="password2" id="password2">
        </div>
        <div class="start dataF">
             <button>зарегестрироваться</button>
        </div>
        <a class="have" href="{% url "user:sign-in" %}">У меня есть аккаунт</a>
    </form>
<!--    DO IT-->
    <form method="post" class="secon block none">
        {% csrf_token %}
        <p class="emailP"></p>
        <p class="tries">осталось попыток 5</p>
        <label for="code">Введите код</label>
        <div class="input code">
            <input type="text" name="code" id="code">
        </div>
        <div class="start emailF">
             <button>продолжить</button>
        </div>
        <div class="back">
            <a href="{% url "user:sign-up" %}">назад</a>
        </div>
    </form>

    <script
        src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
        crossorigin="anonymous">
    </script>
    <script src="{% static "user/js/sign-up.js" %}"></script>
</body>
</html>